### ISSUE TITLE
[Bug]: "download_loader" is missing

### ISSUE THREAD

**Issue by Kulkarni-mohit** [run-llama/llama_index#10667]
### Bug Description

"download_loader" is missing from llama-index.core in version 0.10.x
previously I used to import download_loader as 
`from llama_index.core import download_loader`

### Version

0.10.3

### Steps to Reproduce

`from llama_index.core import download_loader`

### Relevant Logs/Tracbacks

ImportError                               Traceback (most recent call last)
[<ipython-input-40-150d3ae238a1>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from llama_index.core import download_loader

ImportError: cannot import name 'download_loader' from 'llama_index.core' (/usr/local/lib/python3.10/dist packages/llama_index/core/__init__.py)

**Comment by logan-markewich** [comment]
@Kulkarni-mohit please update `pip install -U llama-index llama-index-core`, this was fixed in v0.10.3

This works in a fresh colab
https://colab.research.google.com/drive/17UD8UI6KQSlxB1_AAshmP62hhQCbRdmm?usp=sharing

FYI, download loader is depreceted, you should `pip install ...` the specific package. A registry of packages is here: https://pretty-sodium-5e0.notion.site/ce81b247649a44e4b6b35dfb24af28a6?v=53b3c2ced7bb4c9996b81b83c9f01139

The llamahub website will also be updated soon

**Comment by Kulkarni-mohit** [comment]
It worked now, thanks.

**Comment by MatteoBelvederesi-NewTechnology** [comment]
works but this is a mess.

**Comment by RemoSande** [comment]
Im still getting the following error depsite several attemps :

> ---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], [line 1](vscode-notebook-cell:?execution_count=1&line=1)
----> [1](vscode-notebook-cell:?execution_count=1&line=1) from llama_index import download_loader

ImportError: cannot import name 'download_loader' from 'llama_index' (unknown location)

**Comment by psylone** [comment]
> Im still getting the following error depsite several attemps :
> 
> `--------------------------------------------------------------------------- ImportError Traceback (most recent call last) Cell In[1], line 1 ----> 1 from llama_index import download_loader
> 
> ImportError: cannot import name 'download_loader' from 'llama_index' (unknown location) `

At least for `v0.10.38` of llama-index you can do this:

```python
from llama_index.core import download_loader
```

But it's deprecated in favor of separate packages. For example, instead of this:

```python
from llama_index.core import download_loader

WikipediaReader = download_loader("WikipediaReader")
```

install a separate package: `pip install llama-index-readers-wikipedia` and then import:

```python
from llama_index.readers.wikipedia import WikipediaReader
```

You can find more readers on [LlamaHub](https://llamahub.ai/?tab=readers).
