### ISSUE TITLE
[Bug]: Breaking Image/Index node fetching behavior after refactor

### ISSUE THREAD

**Issue by dgonsan** [run-llama/llama_index#19499]
### Bug Description

We have a simple retrieval process that just performs a query using the query engine on our vector store (OpenSearch) and then uses that data to generate the query response.

This was working fine until version 0.12.49 when the refactor in this pull request was introduced: https://github.com/run-llama/llama_index/pull/19382 

Previously when a Image or Index nodes were not found in the document store (there was a check for it `self._docstore.document_exists(node_id)`) the node from the vector store was returned. With the changes those node types are always fetched from the document store and it they don't exist it fails with the error`ValueError: Document {node_id} is not a Node.` as explained in the bug https://github.com/run-llama/llama_index/issues/19473

As we have all the information needed to build the nodes in the vector store we don't need a persistent document store to store that data, that was working fine until the check for document existence was removed in the refactor, after that all the queries that return an Image/Index node fail because they cannot be retrieved and they will never exist.

This is a big breaking change for our use case as those queries went from working fine to not working at all.

### Version

0.12.49

### Steps to Reproduce

To reproduce the issue you just need to create an OpenSearch vector store without a persistent document store and insert some Image/Index nodes, when retrieving that data using the query engine with llama core version >0.12.49 it fails with the `ValueError: Document {node_id} is not a Node.` as it cannot find the node in the document store.

If llama core version is downgrade to 0.12.48 without any other change then the queries work as expected.

### Relevant Logs/Tracbacks

```shell

```

**Comment by logan-markewich** [comment]
@dgonsan can you confirm if 0.12.51 has the same issue?

**Comment by logan-markewich** [comment]
Also its super unclear how to reproduce this, a minimal example would help a ton, otherwise I'm bumbling around guessing

**Comment by strawgate** [comment]
@logan-markewich I think it's just this https://github.com/run-llama/llama_index/issues/19473, ill take a look and try to figure out why its only happening now

**Comment by strawgate** [comment]
https://github.com/run-llama/llama_index/pull/19501

**Comment by strawgate** [comment]
the simple vector store doesnt store text so i wrote an ad-hoc test

```

def test_query_vector_or_docstore() -> None:
    """Test embedding query."""
    duckdb_vector_store = DuckDBVectorStore()
    image_node = ImageNode(image="tomato")
    text_node = TextNode(text="potato")

    index = VectorStoreIndex.from_vector_store(duckdb_vector_store)
    index.insert_nodes([image_node, text_node])

    # Remove the image node so that we just get whatever is in the vector store
    index.docstore.delete_document(image_node.node_id)

    # test embedding query
    query_str = "What is?"
    retriever = index.as_retriever()
    results = retriever.retrieve(QueryBundle(query_str))

    assert len(results) == 2


    image_node = next(node for node in results if isinstance(node.node, ImageNode))
    text_node = next(node for node in results if isinstance(node.node, TextNode) and not isinstance(node.node, ImageNode))

    assert image_node.node.node_id == image_node.node_id
    assert isinstance(image_node.node, ImageNode)
    assert image_node.node.image == ""
    assert text_node.node.node_id == text_node.node_id
    assert isinstance(text_node.node, TextNode)
    assert text_node.node.text == "potato"
```

**Comment by dgonsan** [comment]
@logan-markewich I tested all versions from 0.12.49 to 0.12.51 and all of them experience the same issue.

The minimal code to reproduce it is:

```
endpoint = os.getenv('OPENSEARCH_ENDPOINT')
user = os.getenv("OPENSEARCH_USER")
pwd = os.getenv("OPENSEARCH_PASSWORD")

client = OpensearchVectorClient(endpoint=endpoint, http_auth=(user, pwd), index="test-index", dim=1536)
vector_store = OpensearchVectorStore(client)
index = VectorStoreIndex.from_vector_store(vector_store)

image_node = ImageNode(text="Test Image", image_url="https://test.com/image.jpg")
index.build_index_from_nodes(nodes=[image_node])

query_engine = index.as_query_engine()
res = query_engine.query("Test Image")
print(res)
print(res.source_nodes)
```

With 0.12.48 you get "An image that is being used for testing purposes." as a response and the imageNode in the source_nodes list.

If you update to any other version then you get the `ValueError: Document {node_id} is not a Node.` exception when trying to execute the same code.

The error ends up in https://github.com/run-llama/llama_index/issues/19473 as @strawgate said, before the code didn't get to the get_node function as it had a check to see if the document was in the document store, so the get was never tried if it wasn't there. So fixing that bug may be an option too.

**Comment by logan-markewich** [comment]
@dgonsan fyi, users aren't meant to use `index.build_index_from_nodes()` directly (this really should have been a private method, but far too late/breaking to change that now)

**Comment by strawgate** [comment]
fyi fix has been merged, if you can verify your use-case is fixed by using main that would be helpful

**Comment by logan-markewich** [comment]
(I also released this in 0.12.52)

**Comment by strawgate** [comment]
@logan-markewich thanks for tagging me on the PR, not sure I would have seen this if not, sorry for all the commotion and 🤞 this resolved the issue

**Comment by dgonsan** [comment]
@strawgate Tested with 0.12.52 and it's working fine again. Thanks for your help.

**Comment by dgonsan** [comment]
@strawgate  Sorry, it seems that I made a mistake while testing it, probably used a venv with the old dependency in it. Testing it again today I'm still getting the same error with 0.12.52 as the default raise_error is True for the **get_node** function in **BaseDocumentStore** even if we pass False to the **get_nodes** (note the plural here), so the configuration is not respected.

```
def get_node(self, node_id: str, raise_error: bool = True) -> Optional[BaseNode]:
        """
        Get node from docstore.

        Args:
            node_id (str): node id
            raise_error (bool): raise error if node_id not found

        """
        doc = self.get_document(node_id, raise_error=raise_error)

        if doc is None:
            # The doc store should have raised an error if the node_id is not found, but it didn't
            # so we raise an error here
            if raise_error:
                raise ValueError(f"Node {node_id} not found")
            return None

        # The document should always be a BaseNode, but we check to be safe
        if not isinstance(doc, BaseNode):
            raise ValueError(f"Document {node_id} is not a Node.")

        return doc
```

Code from **get_nodes** that doesn't use the raise_error value when calling **get_node** if it's False:
```
if raise_error:
            return [node for node_id in node_ids if (node := self.get_node(node_id, raise_error=True))]
        else:
            return [self.get_node(node_id) for node_id in node_ids]
```

I tried modifying the code passing the raise_error value to False there:
```
if raise_error:
            return [node for node_id in node_ids if (node := self.get_node(node_id, raise_error=True))]
        else:
            return [self.get_node(node_id, raise_error=False) for node_id in node_ids]
```

And then we get the expected None value from that function but then it fails in the **_insert_fetched_nodes_into_query_result** function in **VectorIndexRetriever** class when it tries to build the id to nodes dict
```
        fetched_nodes_by_id: Dict[str, BaseNode] = {
            str(node.node_id): node for node in fetched_nodes
        }
```
As node is None this fails with an AttributeError accessing the node_id property.

Modifying that line to check for None values fixes that issue and we get the response and the source node back:
```
        fetched_nodes_by_id: Dict[str, BaseNode] = {
            str(node.node_id): node for node in fetched_nodes if node is not None
        }
```

**Comment by strawgate** [comment]
okay yeah, the commit that added the if/else fails the duckdb test because it is returning `None` into the result.

Will make a PR shortly

**Comment by strawgate** [comment]
PR linked

**Comment by strawgate** [comment]
I was able to reproduce and my reproduction is fixed with the PR

@dgonsan are you able to test against main so we can be sure it's fixed before merging?

**Comment by dgonsan** [comment]
@strawgate I tested with tha llama core from the PR branch and with those changes I get the results back using the OpenSearch vector store.

**Comment by strawgate** [comment]
@dgonsan so good to go with the add't pr? @logan-markewich

**Comment by dgonsan** [comment]
I just did another check after the merge using the main branch and everything looks good.

Thanks everyone for the fix.

**Comment by strawgate** [comment]
Hopefully the speedup from the original change at least somewhat makes up for the hassle :)
